default_language_version:
  python: python3
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.5
  hooks:
    - id: ruff-format
    - id: ruff
      args: [ --fix ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
- repo: https://github.com/haizaar/check-pipfile-lock
  rev: v0.0.3
  hooks:
    - id: check-pipfile-lock
